version: '3'
    
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=new
      - POSTGRES_USER=omar
      - POSTGRES_PASSWORD=010
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment: 
      - SECRET_KEY=dn*1(+4sp7**yo^1&54d)qgr=5_gun-tn+t#_br2-9=&8w+^fg
      - DEBUG=1
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_n3DWSzpAX1QV9lnXMKfUAVwj00yh4TkVLs
      - STRIPE_TEST_SECRET_KEY=sk_test_1xizpupjubiivLLyvj41WbW900U8jL6zaz
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db